In [1]:
import numpy as np
import pandas as pd
import pickle
import datetime

In [35]:
kenner = pd.read_pickle('kenner_scrape.pkl')

In [36]:
kenner

,ID,max_temp_deg_f,avg_temp_deg_f,min_temp_deg_f,max_dew_point_deg_f,avg_dew_point_deg_f,min_dew_point_deg_f,max_dew_humidity_pct,avg_dew_humidity_pct,min_dew_humidity_pct,max_wind_speed_mph,avg_wind_speed_mph,min_wind_speed_mph,max_pressure_hg,avg_pressure_hg,min_pressure_hg,tot_precipitation_in
0,KMSY_2008-1,54,49.1,41,44,26.4,18,69,42.7,26,21,15.3,8,30.6,30.5,30.3,0.00
1,KMSY_2008-1,43,37.9,33,22,15.0,11,56,39.8,31,24,17.8,13,30.8,30.7,30.6,0.00
2,KMSY_2008-1,41,34.9,28,25,18.5,9,64,52.3,28,16,8.5,0,30.8,30.8,30.6,0.00
3,KMSY_2008-1,62,51.5,39,50,38.9,0,83,69.5,50,17,10.2,5,30.6,30.5,30.4,0.00
4,KMSY_2008-1,71,61.4,55,59,55.2,51,93,80.5,61,16,10.7,6,30.4,30.3,30.2,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,KMSY_2020-12,67,54.5,40,49,44.0,35,85,69.0,52,13,5.7,0,30.2,30.2,30.1,0.00
4742,KMSY_2020-12,72,60.1,49,53,49.6,45,86,69.9,48,8,5.2,0,30.3,30.3,30.2,0.00
4743,KMSY_2020-12,72,61.5,50,59,53.4,47,89,76.1,55,14,8.6,3,30.3,30.2,30.1,0.00
4744,KMSY_2020-12,77,68.5,61,62,59.4,55,86,74.0,46,22,12.6,6,30.1,30.0,29.9,0.00
4745,KMSY_2020-12,76,71.0,64,70,65.8,54,90,83.7,69,24,15.4,9,29.9,29.8,29.8,0.01

In [37]:
kenner = kenner[['ID', 'avg_temp_deg_f', 'avg_dew_humidity_pct', 'avg_wind_speed_mph', 'tot_precipitation_in']]
kenner

,ID,avg_temp_deg_f,avg_dew_humidity_pct,avg_wind_speed_mph,tot_precipitation_in
0,KMSY_2008-1,49.1,42.7,15.3,0.00
1,KMSY_2008-1,37.9,39.8,17.8,0.00
2,KMSY_2008-1,34.9,52.3,8.5,0.00
3,KMSY_2008-1,51.5,69.5,10.2,0.00
4,KMSY_2008-1,61.4,80.5,10.7,0.00
...,...,...,...,...,...
4741,KMSY_2020-12,54.5,69.0,5.7,0.00
4742,KMSY_2020-12,60.1,69.9,5.2,0.00
4743,KMSY_2020-12,61.5,76.1,8.6,0.00
4744,KMSY_2020-12,68.5,74.0,12.6,0.00
4745,KMSY_2020-12,71.0,83.7,15.4,0.01

In [38]:
kenner[['avg_temp_deg_f', 'avg_dew_humidity_pct', 'avg_wind_speed_mph', 'tot_precipitation_in']] = kenner[['avg_temp_deg_f', 'avg_dew_humidity_pct', 'avg_wind_speed_mph', 'tot_precipitation_in']].astype(float)

/Users/dunleavyjason/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3188: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [42]:
kenner[["city", "yyyy-m"]] = kenner.ID.str.split('_', expand = True)

/Users/dunleavyjason/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3188: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [45]:
del kenner["ID"]

In [50]:
kenner.groupby(["city", "yyyy-m"]).aggregate(np.average)

              avg_temp_deg_f  avg_dew_humidity_pct  avg_wind_speed_mph  \
city yyyy-m
KMSY 2008-1        52.841935             74.177419           10.264516
     2008-10       70.283871             68.964516            7.596774
     2008-11       60.713333             69.950000            7.443333
     2008-12       58.577419             75.477419            9.112903
     2008-2        59.306897             74.062069            9.289655
...                      ...                   ...                 ...
     2020-5        77.690323             66.545161            8.480645
     2020-6        83.386667             69.083333            7.443333
     2020-7        84.764516             74.567742            7.200000
     2020-8        83.658065             72.606452            6.870968
     2020-9        79.610000             73.960000            8.670000

              tot_precipitation_in
city yyyy-m
KMSY 2008-1               0.000000
     2008-10              0.000000
     2008-11              0.000000
     2008-12              0.000000
     2008-2               0.000000
...                            ...
     2020-5               0.269677
     2020-6               0.318000
     2020-7               0.498387
     2020-8               0.201613
     2020-9               0.059667

[156 rows x 4 columns]

In [ ]:
group_by